import { Timestamp } from "firebase/firestore";
import { CardForm } from "../models/cardForm.model";

export const initialCardFormData: CardForm = {
  id: "",
  uid: null,
  bio: {
    value: "",
    isRequired: true,
    maxLength: 150,
    label: "한 줄 소개",
    isPublic: true,
  },
  name: {
    value: "",
    isRequired: true,
    maxLength: 50,
    label: "이름/닉네임",
    isPublic: true,
  },
  gender: {
    value: "여성",
    isRequired: true,
    options: ["여성", "남성", "기타/선택안함"],
    otherOption: "",
    label: "성별",
    isPublic: true,
  },
  birth: {
    value: "",
    isRequired: true,
    format: "YYYY-MM-DD",
    label: "생년월일",
    isPublic: false,
  },
  birthday: {
    value: "",
    isRequired: true,
    format: "MM-DD",
    label: "생일",
    isPublic: true,
  },
  age: {
    value: "",
    isRequired: true,
    format: "number",
    label: "나이",
    isPublic: false,
  },
  email: {
    value: "",
    isRequired: false,
    maxLength: 100,
    format: "email",
    label: "이메일",
    isPublic: false,
  },
  sns: {
    value: "",
    isRequired: false,
    options: [
      "인스타그램",
      "트위터(X)",
      "페이스북",
      "카카오톡",
      "라인",
      "기타",
    ],
    otherOption: "",
    maxLength: 100,
    label: "SNS 아이디",
    isPublic: false,
  },
  mbti: {
    value: "",
    isRequired: false,
    options: ["INFJ", "ENFP", "ISTJ", "ENTP"],
    otherOption: "",
    label: "MBTI",
    isPublic: true,
  },
  hobby: {
    value: "",
    isRequired: false,
    maxLength: 50,
    label: "취미/관심사",
    isPublic: true,
  },

  customFields: {
    value: [] as { key: string; value: string; isPublic: boolean }[],
    maxFields: 5,
    recommendedFields: [
      { key: "phone", label: "전화번호", maxLength: 15 },
      { key: "address", label: "주소", maxLength: 200 },
      { key: "job", label: "직업", maxLength: 50 },
      { key: "school", label: "학교", maxLength: 100 },
      { key: "like", label: "좋아하는 것", maxLength: 50 },
      { key: "dislike", label: "싫어하는 것", maxLength: 50 },
    ],
    isPublic: false,
    label: "추가 정보",
  },
  qrCodeUrl: "",
  createdAt: new Date() as unknown as Timestamp,
  updatedAt: null as unknown as Timestamp,
};
